# Generated by Django 5.2.3 on 2025-06-15 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnderweightTips',
            new_name='OverweightTip',
        ),
        migrations.RenameModel(
            old_name='OverweightTips',
            new_name='UnderweightTip',
        ),
    ]
