# Generated by Django 5.2.3 on 2025-06-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_randompopup'),
    ]

    operations = [
        migrations.AddField(
            model_name='overweighttip',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='underweighttip',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
